import docx
import sys

try:
    doc = docx.Document('SmartMBG_Yoga Ari Anggoro_Icasvi_UIUX.docx')
except Exception as e:
    sys.exit(1)

for p in doc.paragraphs:
    if 'Spatial data generated by' in p.text:
        p.text = p.text.replace('Spatial data generated by  were analyzed to observe the distribution of schools, SPPG, and waste management partners.', '')
    
    if 'Meanwhile, the' in p.text and 'module enhances spatial monitoring' in p.text:
        p.text = p.text.replace('Meanwhile, the  module enhances spatial monitoring by providing interactive visualization of schools, SPPG, and waste management partners.', '')

try:
    doc.save('SmartMBG_Yoga Ari Anggoro_Icasvi_UIUX.docx')
except Exception as e:
    pass
